### PR TITLE
Doc update

### PR DESCRIPTION
**Pull request by troutowicz**
Updated Rtype signatures and included the `displayName` property in the API docs.

### CODE REVIEW

**Comment by troutowicz** [comment]
The failed test can be ignored as CircleCI is trying to use a newer version of Babel. We can merge this after merging PR #27.

**Comment by troutowicz** [comment]
Rebased with master after merging #27, but CircleCI is still throwing errors. @ericelliott any ideas?

**Comment by ericelliott** [comment]
Have you tried rebuilding without cache?

**Comment by troutowicz** [comment]
Ah, didn't know about that option. Rebuilding without cache passed. This PR is ready to merge now.

**Pull request merged**
